spring:
  profiles:
    active: local

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_ADDRESS}
    password: ${EMAIL_PASSWORD}
    default-encoding: UTF-8
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret-key: ${SECRET_KEY}
  access-exp: ${ACCESS_EXP}
  refresh_exp: ${REFRESH_EXP}