spring:
  config:
    activate:
      on-profile: test

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:onBoard;MODE=MySQL
    username: sa
    password:

  sql:
    init:
      mode: never

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect

logging.level:
  org.hibernate.SQL: debug