name: CD

on:
  push:
    branches:
      - main

jobs:
    cd:
      runs-on: ubuntu-latest

      needs: [ci, lint]

      steps:
        - uses: actions/checkout@v3

        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'zulu'

        - name: Set up .jar
          run: ./gradlew bootJar

        - name: Publish to Registry
          uses: elgohr/Publish-Docker-Github-Action@v5
          with:
            name: ${{ secrets.DOCKER_REPOSITORY }}
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Deploy For EC2
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.EC2_HOST }}
            port: ${{ secrets.EC2_SSH_PORT }}
            username: ${{ secrets.EC2_USERNAME }}
            key: ${{ secrets.EC2_SSH_KEY }}
            script: |
              docker rm -f ${{ secrets.DOCKER_CONTAINER_NAME }}
              docker pull ${{ secrets.DOCKER_REPOSITORY }}
              cd ${{ secrets.DIRECTORY }}
              docker run -dp ${{ secrets.SPRING_HOST_PORT }}:${{ secrets.SPRING_CONTAINER_PORT }} --name ${{ secrets.DOCKER_CONTAINER_NAME }} --env-file .env ${{ secrets.DOCKER_REPOSITORY }}