name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js 21.x
      uses: actions/setup-node@v3
      with:
        node-version: 21.x
        cache: 'npm'

    - run: npm ci

    - name: Build
      run: npm run build --if-present
    
    - name: Test
      run: npm test
